import { useMemo, useState } from 'react';
import { skills, topics } from '../data/skills';

export function Navbar() {
  const links = ['skills','practice','planner','nine-mark','checklist','feedback'];
  return <nav className="sticky top-0 z-20 bg-white border-b"><div className="max-w-6xl mx-auto p-4 flex gap-4 flex-wrap">{links.map(l=><a key={l} href={`#${l}`} className="text-sm text-slate-700 hover:text-blue-700 capitalize">{l.replace('-',' ')}</a>)}</div></nav>
}

export function SkillCard({ skill, onOpen }) {
  return <div className="bg-white rounded-xl shadow-sm border p-4 flex flex-col gap-2"><h3 className="font-semibold text-slate-900">{skill.title}</h3><p className="text-sm text-slate-600">{skill.meaning}</p><p className="text-xs text-emerald-700">Example: {skill.example}</p><button onClick={()=>onOpen(skill)} className="mt-auto bg-blue-600 text-white rounded-lg px-3 py-2 text-sm">Practice this skill</button></div>
}

export function SkillDetail({ skill, onClose }) {
  if (!skill) return null;
  return <div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4 z-30"><div className="bg-white max-w-2xl w-full rounded-xl p-6 space-y-3"><h2 className="text-2xl font-bold">{skill.title}</h2><p><b>Explanation:</b> {skill.explanation}</p><p><b>Why this matters:</b> {skill.why}</p><p><b>ESS example:</b> {skill.example}</p><p><b>Common mistake:</b> {skill.mistake}</p><p><b>Examiner tip:</b> {skill.tip}</p><p><b>Practice task:</b> {skill.task}</p><button className="bg-slate-800 text-white px-3 py-2 rounded" onClick={onClose}>Close</button></div></div>
}

export function QuestionGenerator(){
  const [topic,setTopic]=useState(topics[0]); const [mark,setMark]=useState('9'); const [term,setTerm]=useState('To what extent');
  const question = useMemo(()=>`${term} ${mark==='4'?'how':mark==='7'?'the effectiveness of':'can'} ${topic.toLowerCase()} ${mark==='4'?'affect environmental systems?':mark==='7'?'strategies reduce environmental impacts?':'strategies deliver long-term sustainability?'} `,[topic,mark,term]);
  return <section id="practice" className="bg-white p-5 rounded-xl border"><h2 className="font-bold text-xl mb-3">Essay Question Practice</h2><div className="grid md:grid-cols-3 gap-3"> <select value={topic} onChange={e=>setTopic(e.target.value)} className="border rounded p-2">{topics.map(t=><option key={t}>{t}</option>)}</select><select value={mark} onChange={e=>setMark(e.target.value)} className="border rounded p-2"><option value='4'>4 marks</option><option value='7'>7 marks</option><option value='9'>9 marks</option></select><select value={term} onChange={e=>setTerm(e.target.value)} className="border rounded p-2">{['Explain','Discuss','Evaluate','To what extent'].map(t=><option key={t}>{t}</option>)}</select></div><p className="mt-4 text-emerald-800 font-medium">Generated question: {question}</p></section>
}

export function EssayPlanner(){
  const [mark,setMark]=useState('9'); const [fields,setFields]=useState({}); const [plan,setPlan]=useState('');
  const templates={
    '4':['Key concept','Point 1','Point 2','ESS example','Link back to question'],
    '7':['Key concept','Point 1','Point 2','Point 3/4','ESS terminology','Relevant example','Strength or limitation','Mini conclusion'],
    '9':['Introduction','Argument 1','Argument 2','Counterargument/limitation','ESS example','Balanced judgement','Final conclusion']
  };
  const build=()=>setPlan(templates[mark].map((f,i)=>`${i+1}. ${f}: ${fields[f]||'...'}`).join('\n'));
  return <section id="planner" className="bg-white p-5 rounded-xl border"><h2 className="font-bold text-xl mb-3">Essay Planning Tool</h2><select value={mark} onChange={e=>{setMark(e.target.value);setFields({});setPlan('')}} className="border rounded p-2 mb-4"><option value='4'>4 marks</option><option value='7'>7 marks</option><option value='9'>9 marks</option></select><div className="grid md:grid-cols-2 gap-3">{templates[mark].map(f=><input key={f} placeholder={f} value={fields[f]||''} onChange={e=>setFields({...fields,[f]:e.target.value})} className="border p-2 rounded" />)}</div><button onClick={build} className="mt-4 bg-emerald-700 text-white px-4 py-2 rounded">Generate Essay Plan</button>{plan && <pre className="mt-4 bg-slate-50 p-3 rounded whitespace-pre-wrap">{plan}</pre>}</section>
}

export function NineMarkGuide(){ const items=[['Understanding of concepts and terminology','Define and apply precise ESS concepts to your argument.','Undefined or misused terms reduce clarity.','Use “resilience” to explain ecosystem recovery after disturbance.'],['Breadth in addressing and linking ideas','Link environmental, social, and economic dimensions.','Answers stay narrow and disconnected.','Connect energy policy to emissions, costs, and equity.'],['Use of relevant and well-developed examples','Use specific case studies and explain relevance.','Examples are named but not analysed.','Costa Rica reforestation policy linked to biodiversity gains.'],['Balanced analysis showing multiple perspectives','Compare benefits, limitations, and stakeholders.','One-sided argument with no trade-offs.','Hydropower supports low-carbon energy but alters river habitats.'],['A conclusion that synthesizes the response effectively','End with a justified overall judgement.','Conclusion repeats points without judgement.','“Most effective where governance and funding are strong.”']]; return <section id="nine-mark" className="bg-white p-5 rounded-xl border"><h2 className="font-bold text-xl mb-3">9-Mark Essay Structure Guide</h2><div className="space-y-3">{items.map(i=><div key={i[0]} className="border rounded-lg p-3"><h3 className="font-semibold">{i[0]}</h3><p><b>What to do:</b> {i[1]}</p><p><b>Weak answers miss:</b> {i[2]}</p><p><b>ESS example:</b> {i[3]}</p></div>)}</div><p className="mt-3 text-amber-700 font-medium">All strong 9-mark ESS essays must move beyond description. They must analyse, evaluate, balance perspectives, and reach a supported conclusion.</p></section>}

export function SelfChecklist(){ const items=['Did I identify the command term?','Did I answer the exact question?','Did I use accurate ESS terminology?','Did I include relevant ESS examples?','Did I explain causes, effects, and links?','Did I include more than one perspective?','Did I make a clear judgement?','Did I write a conclusion?','Did I avoid writing memorised content?','Did I manage my time?']; const [c,setC]=useState(Array(items.length).fill(false)); const done=c.filter(Boolean).length; return <section id="checklist" className="bg-white p-5 rounded-xl border"><h2 className="font-bold text-xl mb-3">Self-Assessment Checklist</h2>{items.map((it,idx)=><label key={it} className="flex gap-2 py-1"><input type="checkbox" checked={c[idx]} onChange={()=>setC(c.map((v,i)=>i===idx?!v:v))}/><span>{it}</span></label>)}<p className="mt-3 font-medium text-blue-800">You completed {done}/10 essay-writing checks.</p></section>}

export function FeedbackSimulator(){ const [txt,setTxt]=useState(''); const [out,setOut]=useState(null); const run=()=>{ const low=txt.toLowerCase(); const strengths=[]; if(/biodiversity|sustainability|resilience|mitigation|adaptation/.test(low)) strengths.push('You used relevant ESS terminology.'); if(/for example|for instance|case study|such as/.test(low)) strengths.push('You included at least one example to support your point.'); const improve=[]; if(!/however|on the other hand|limitation|although/.test(low)) improve.push('Add a counterargument or limitation to make the analysis balanced.'); if(!/therefore|overall|to what extent|in conclusion/.test(low)) improve.push('Include a clear final judgement linked to the command term.'); if(!/because|leads to|results in/.test(low)) improve.push('Explain causal links more clearly to move beyond description.'); setOut({strengths:strengths.length?strengths:['Your response is clear and on-topic.'],improve,next:'Revise one paragraph by adding a limitation, a cause-effect link, and a final supported judgement.'});}; return <section id="feedback" className="bg-white p-5 rounded-xl border"><h2 className="font-bold text-xl mb-3">Examiner Feedback Simulator</h2><textarea className="w-full border rounded p-2 min-h-32" placeholder="Paste a short ESS response..." value={txt} onChange={e=>setTxt(e.target.value)} /><button onClick={run} className="mt-3 bg-blue-700 text-white px-4 py-2 rounded">Analyse Response</button>{out&&<div className="mt-4 grid md:grid-cols-3 gap-3 text-sm"><div className="bg-emerald-50 p-3 rounded"><h3 className="font-semibold">Strengths</h3><ul>{out.strengths.map(s=><li key={s}>• {s}</li>)}</ul></div><div className="bg-amber-50 p-3 rounded"><h3 className="font-semibold">Areas to Improve</h3><ul>{out.improve.map(s=><li key={s}>• {s}</li>)}</ul></div><div className="bg-blue-50 p-3 rounded"><h3 className="font-semibold">Next Step</h3><p>{out.next}</p></div></div>}</section>}
